name: smart_pantry_inventory
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # DI
  get_it: ^7.7.0

  # Functional programming
  dartz: ^0.10.1

  # Routing
  auto_route: ^9.2.2

  # Local database
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Key-value / cache
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # JSON
  json_annotation: ^4.9.0

  # ML Kit
  google_mlkit_barcode_scanning: ^0.12.0
  google_mlkit_text_recognition: ^0.13.0

  # Live barcode scanner camera
  mobile_scanner: ^5.1.1

  image_picker: ^1.1.2

  # Env
  flutter_dotenv: ^5.1.0

  # UI helper
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0

  mocktail: ^1.0.4
  bloc_test: ^9.1.0
  integration_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env